import UIKit

// THIS FILE IS AUTOGENERATED, DO NOT EDIT BY HAND
// swiftlint:disable file_length type_body_length line_length superfluous_disable_command extension_access_modifier
public extension UIImage {
    enum TVShows {}
}

extension UIImage.TVShows {

    public static var icCheckboxSelected: UIImage { return UIImage(named: "ic-checkbox-selected", in: .main, compatibleWith: nil)! }
    public static var icCheckboxUnselected: UIImage { return UIImage(named: "ic-checkbox-unselected", in: .main, compatibleWith: nil)! }
    public static var icInvisible: UIImage { return UIImage(named: "ic-invisible", in: .main, compatibleWith: nil)! }
    public static var icLogoWhite: UIImage { return UIImage(named: "ic-logo-white", in: .main, compatibleWith: nil)! }
    public static var icProfile: UIImage { return UIImage(named: "ic-profile", in: .main, compatibleWith: nil)! }
    public static var icProfilePlaceholder: UIImage { return UIImage(named: "ic-profile-placeholder", in: .main, compatibleWith: nil)! }
    public static var icShowDeselected: UIImage { return UIImage(named: "ic-show-deselected", in: .main, compatibleWith: nil)! }
    public static var icShowPlaceholderRectangle: UIImage { return UIImage(named: "ic-show-placeholder-rectangle", in: .main, compatibleWith: nil)! }
    public static var icShowPlaceholderVertical: UIImage { return UIImage(named: "ic-show-placeholder-vertical", in: .main, compatibleWith: nil)! }
    public static var icShowSelected: UIImage { return UIImage(named: "ic-show-selected", in: .main, compatibleWith: nil)! }
    public static var icStarDeselected: UIImage { return UIImage(named: "ic-star-deselected", in: .main, compatibleWith: nil)! }
    public static var icStarDeselectedLarge: UIImage { return UIImage(named: "ic-star-deselected-large", in: .main, compatibleWith: nil)! }
    public static var icStarSelected: UIImage { return UIImage(named: "ic-star-selected", in: .main, compatibleWith: nil)! }
    public static var icStarSelectedLarge: UIImage { return UIImage(named: "ic-star-selected-large", in: .main, compatibleWith: nil)! }
    public static var icTopRatedDeselected: UIImage { return UIImage(named: "ic-top-rated-deselected", in: .main, compatibleWith: nil)! }
    public static var icTopRatedSelected: UIImage { return UIImage(named: "ic-top-rated-selected", in: .main, compatibleWith: nil)! }
    public static var icTopRated1Deselected: UIImage { return UIImage(named: "ic-top-rated1-deselected", in: .main, compatibleWith: nil)! }
    public static var icTopRated1Selected: UIImage { return UIImage(named: "ic-top-rated1-selected", in: .main, compatibleWith: nil)! }
    public static var icVisible: UIImage { return UIImage(named: "ic-visible", in: .main, compatibleWith: nil)! }
    public static var logoWhite: UIImage { return UIImage(named: "logo-white", in: .main, compatibleWith: nil)! }
    public static var splashTopLeft: UIImage { return UIImage(named: "splash-top-left", in: .main, compatibleWith: nil)! }
    public static var splashTopRight: UIImage { return UIImage(named: "splash-top-right", in: .main, compatibleWith: nil)! }
}
